services:
  app:
    image: slmingol/nyt-connections-clone:latest
    container_name: nyt-connections-clone
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - connections-network

networks:
  connections-network:
    driver: bridge
